apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo-service:27017/ecommerce-app"
  JWT_SECRET: "secret"
  JWT_EXPIRES_IN: "1h"
  CLOUD_NAME: "dtxui3q64"
  CLOUDINARY_API_KEY: "354785718873432"
  CLOUDINARY_SECRET: "7lE6p1_Aj0rBeTZ8JnpF5DXBa-I"
  ADMIN_EMAIL: "alegnta88@gmail.com"
  ADMIN_PASSWORD: "alegnta"
  SMS_API_URL: "http://196.190.251.17/send"
  SMS_SENDER_NAME: "6575"
  SMS_API_KEY: "RGlnYWZDQzpARGlnYWZjYw=="
  CHAPA_TEST_PUBLIC_KEY: "CHAPUBK_TEST-mZ02IQCeuqbkDgVTUxYoP4Bu2G00XcPW"
  CHAPA_SECRET_KEY: "CHASECK_TEST-xhqCd42j74BsCHNl68iI3RYehUPNqXrD"
  ENCRRYPTION_KEY: "o9CpjK82eMD8qZgJe5F8RKM5"
  BASE_URL: "http://localhost:5000"
  STRIPE_SECRET_KEY: "sk_test_51SPTYtRvV45xgAoAsUGGu8V3aTcWf9xc8Ohm4ICLPxcVntoxcBf5PGnjreeTRE00rzlrcKIsW1AxBeYOEQQjB3Hl00fEIUVKYu"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51SPTYtRvV45xgAoA9tOJfj53bsbAGn2Wjw4nH3wDF7fkcPmQkIpXKyAf6d9WUgESH8GXbohoWeoezQLre3z6m2A300LqvQAq7h"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_USER: "alegntapay@gmail.com"
  EMAIL_PASSWORD: "asnr dykw jfdw xdnu"
  REDIS_URL: "redis://redis-service:6379"
